
a = 987
d = 78
b = ("the hello")
c = True
# if (a>d):
#     print(True)
#     if(a==987):
#         print(a)
#     else:
#         print(i)
# elif(a==d):
#     print("equal")
# else:
#     print(False)

# print(b.swapcase())
# print(b.istitle())
# print(b.islower())
# print(b.isalpha())
# print(b.isalnum()) #even giving space will be show false
# print(b.endswith("!")) # ans is in true false
# print(b.count("!"))
# print(b.rstrip("!"))
# b = input("the hEllo".strip())
# print(b.capitalize())
# print(b.split("split"))
# print(b.center(50))
# print(b.lower())
# print(b.index("hello"))
# print(b.title())
# print(b.upper())
# print("hello world ")
# print("""hello you are a terrr
    #   sjhsjsjfsfsfjbsfhb""")
# print(b[1])
# print(str(b.index('e')))  
# This will print '1', which is the index of 'e' in "hello"

# print(b.find("the"))
# print(b.index("hello"))
# print(b.title())
# print(b.upper())
# print("hello world ")
# print("""hello you are a terrr
    #   sjhsjsjfsfsfjbsfhb""")
# print(b[1])
# print(str(b.index('e')))  
# This will print '1', which is the index of 'e' in "hello"
# for i in range(10):
#     i=i+2
#     print(i)

